import type { DefaultSharedModuleContext, LangiumServices, LangiumSharedServices, Module, PartialLangiumServices } from 'langium';
import { createDefaultModule, createDefaultSharedModule, inject } from 'langium';
import { WorkoutPlanningGeneratedModule, WorkoutPlanningGeneratedSharedModule } from './generated/module.js';
import { WorkoutPlanningValidator, registerValidationChecks } from './workout-planning-validator.js';

/**
 * Declaration of custom services - add your own service classes here.
 */
export type WorkoutPlanningAddedServices = {
    validation: {
        WorkoutPlanningValidator: WorkoutPlanningValidator
    }
}

/**
 * Union of Langium default services and your custom services - use this as constructor parameter
 * of custom service classes.
 */
export type WorkoutPlanningServices = LangiumServices & WorkoutPlanningAddedServices

/**
 * Dependency injection module that overrides Langium default services and contributes the
 * declared custom services. The Langium defaults can be partially specified to override only
 * selected services, while the custom services must be fully specified.
 */
export const WorkoutPlanningModule: Module<WorkoutPlanningServices, PartialLangiumServices & WorkoutPlanningAddedServices> = {
    validation: {
        WorkoutPlanningValidator: () => new WorkoutPlanningValidator()
    }
};

/**
 * Create the full set of services required by Langium.
 *
 * First inject the shared services by merging two modules:
 *  - Langium default shared services
 *  - Services generated by langium-cli
 *
 * Then inject the language-specific services by merging three modules:
 *  - Langium default language-specific services
 *  - Services generated by langium-cli
 *  - Services specified in this file
 *
 * @param context Optional module context with the LSP connection
 * @returns An object wrapping the shared services and the language-specific services
 */
export function createWorkoutPlanningServices(context: DefaultSharedModuleContext): {
    shared: LangiumSharedServices,
    WorkoutPlanning: WorkoutPlanningServices
} {
    const shared = inject(
        createDefaultSharedModule(context),
        WorkoutPlanningGeneratedSharedModule
    );
    const WorkoutPlanning = inject(
        createDefaultModule({ shared }),
        WorkoutPlanningGeneratedModule,
        WorkoutPlanningModule
    );
    shared.ServiceRegistry.register(WorkoutPlanning);
    registerValidationChecks(WorkoutPlanning);
    return { shared, WorkoutPlanning };
}
